#############################################################################
# Makefile for building: OpenVaccine.app/Contents/MacOS/OpenVaccine
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  OpenVaccine.pro
# Template: app
# Command: /Users/yezune/Qt5.5.0/5.5/clang_64/bin/qmake -o Makefile OpenVaccine.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtSvg.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -F/Users/yezune/Qt5.5.0/5.5/clang_64/lib
QMAKE         = /Users/yezune/Qt5.5.0/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = OpenVaccine1.0.0
DISTDIR = /Users/yezune/projects/OV/OpenVaccine/.tmp/OpenVaccine1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -stdlib=libc++ -mmacosx-version-min=10.7 -Wl,-rpath,/Users/yezune/Qt5.5.0/5.5/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/yezune/Qt5.5.0/5.5/clang_64/lib -framework QtQuick -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework QtQml -framework QtNetwork -framework QtSvg -framework QtWidgets -framework QtXml -framework QtConcurrent -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		appmodel.cpp \
		sha1.cpp qrc_qml.cpp \
		moc_appmodel.cpp
OBJECTS       = main.o \
		appmodel.o \
		sha1.o \
		qrc_qml.o \
		moc_appmodel.o
DIST          = ../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		OpenVaccine.pro appmodel.h \
		sha1.h \
		bloom_filter.h main.cpp \
		appmodel.cpp \
		sha1.cpp
QMAKE_TARGET  = OpenVaccine
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = OpenVaccine.app/Contents/MacOS/OpenVaccine

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d OpenVaccine.app/Contents/MacOS/ || mkdir -p OpenVaccine.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpenVaccine.pro ../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		deployment.pri \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf \
		OpenVaccine.pro \
		qml.qrc \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/QtQuick.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtSvg.framework/QtSvg.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/QtQml.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/QtXml.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl \
		/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile OpenVaccine.pro
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
deployment.pri:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/c++11.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/uic.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt5.5.0/5.5/clang_64/mkspecs/features/lex.prf:
OpenVaccine.pro:
qml.qrc:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/QtQuick.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtSvg.framework/QtSvg.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/QtQml.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/QtNetwork.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/QtXml.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/QtConcurrent.prl:
/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile OpenVaccine.pro

qmake_all: FORCE

OpenVaccine.app/Contents/PkgInfo: 
	@test -d OpenVaccine.app/Contents || mkdir -p OpenVaccine.app/Contents
	@$(DEL_FILE) OpenVaccine.app/Contents/PkgInfo
	@echo "APPL????" > OpenVaccine.app/Contents/PkgInfo
OpenVaccine.app/Contents/Resources/empty.lproj: 
	@test -d OpenVaccine.app/Contents/Resources || mkdir -p OpenVaccine.app/Contents/Resources
	@touch OpenVaccine.app/Contents/Resources/empty.lproj
	
OpenVaccine.app/Contents/Info.plist: 
	@test -d OpenVaccine.app/Contents || mkdir -p OpenVaccine.app/Contents
	@$(DEL_FILE) OpenVaccine.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@BUNDLEIDENTIFIER@,org.actus.OpenVaccine,g" -e "s,@ICON@,,g" -e "s,@EXECUTABLE@,OpenVaccine,g" -e "s,@TYPEINFO@,????,g" ../../../Qt5.5.0/5.5/clang_64/mkspecs/macx-clang/Info.plist.app >OpenVaccine.app/Contents/Info.plist

all: Makefile \
		OpenVaccine.app/Contents/PkgInfo \
		OpenVaccine.app/Contents/Resources/empty.lproj \
		OpenVaccine.app/Contents/Info.plist $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents appmodel.h sha1.h bloom_filter.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp appmodel.cpp sha1.cpp $(DISTDIR)/
	$(COPY_FILE) --parents /Users/yezune/projects/OV/OpenVaccine/translations/OpenVaccine_ko.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r OpenVaccine.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		MainForm.ui.qml \
		About.qml \
		main.qml \
		images/needle.png \
		images/icon.png \
		images/bg320x640.png \
		images/titleBar_nanumgodic.svg \
		images/backgroundSvg.svg \
		images/background.png \
		images/overlay.png \
		images/needle_shadow.png \
		images/titleBar.svg \
		images/titleBar_Korean.svg \
		components/Dial.qml
	/Users/yezune/Qt5.5.0/5.5/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_appmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_appmodel.cpp
moc_appmodel.cpp: ../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		bloom_filter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h \
		appmodel.h
	/Users/yezune/Qt5.5.0/5.5/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 -D__APPLE_CC__ -I/Users/yezune/Qt5.5.0/5.5/clang_64/mkspecs/macx-clang -I/Users/yezune/projects/OV/OpenVaccine -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtSvg.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtWidgets.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtGui.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtXml.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/Headers -I/Users/yezune/Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers -F/Users/yezune/Qt5.5.0/5.5/clang_64/lib appmodel.h -o moc_appmodel.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp ../../../Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/QSslSocket \
		../../../Qt5.5.0/5.5/clang_64/lib/QtNetwork.framework/Headers/qsslsocket.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/QtQuick \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qtquickglobal.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/designersupport.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickframebufferobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickitem.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickitemgrabresult.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickrendercontrol.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquicktextdocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickview.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickwindow.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qquickimageprovider.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgabstractrenderer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsggeometry.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgmaterial.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgnode.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgengine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgflatcolormaterial.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgsimplematerial.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgsimplerectnode.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgsimpletexturenode.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgtexture.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgtexturematerial.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgtextureprovider.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qsgvertexcolormaterial.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtQuick.framework/Headers/qtquickversion.h \
		appmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		bloom_filter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

appmodel.o: appmodel.cpp ../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonArray \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDir \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDirIterator \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdiriterator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		appmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtConcurrent.framework/Headers/qtconcurrentrun.h \
		bloom_filter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QException \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h \
		sha1.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QtCore \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpauseanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qendian.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qflags.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qglobalstatic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qisenum.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlibraryinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocessordetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsystemdetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtypeinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtypetraits.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfiledevice.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfileselector.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qiodevice.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlockfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qresource.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsavefile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstorageinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtemporarydir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurlquery.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringlistmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonvalue.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbasictimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimedata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsocketnotifier.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qwineventnotifier.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimedatabase.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimetype.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfactoryinterface.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlibrary.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpluginloader.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstracttransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeventtransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfinalstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qhistorystate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsignaltransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstatemachine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qatomic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qgenericatomic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qreadwritelock.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qresultstore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrunnable.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsemaphore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthreadstorage.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qalgorithms.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydataops.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydatapointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbitarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraylist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcache.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qchar.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcollator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineoption.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcontainerfwd.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcontiguouscache.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeasingcurve.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qiterator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qline.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlinkedlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlocale.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmargins.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qqueue.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrefcount.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qset.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qshareddata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstack.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringbuilder.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringmatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimezone.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvarlengtharray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o appmodel.o appmodel.cpp

sha1.o: sha1.cpp sha1.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/QtCore \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qparallelanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpauseanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpropertyanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsequentialanimationgroup.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariantanimation.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextcodec.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcompilerdetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qendian.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qflags.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qglobal.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qglobalstatic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qisenum.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlibraryinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qnamespace.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qnumeric.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocessordetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsysinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsystemdetection.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtypeinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtypetraits.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbuffer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdatastream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdiriterator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfiledevice.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfileinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfileselector.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfilesystemwatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qiodevice.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlockfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qloggingcategory.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qprocess.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qresource.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsavefile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsettings.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstandardpaths.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstorageinfo.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtemporarydir.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtemporaryfile.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextstream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurl.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qurlquery.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractitemmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qidentityproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qitemselectionmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsortfilterproxymodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringlistmodel.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qjsonvalue.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstracteventdispatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractnativeeventfilter.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbasictimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreapplication.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcoreevent.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeventloop.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmath.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmetaobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmetatype.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimedata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobjectcleanuphandler.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qobjectdefs.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsharedmemory.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsignalmapper.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsocketnotifier.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsystemsemaphore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtranslator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvariant.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qwineventnotifier.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimedatabase.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmimetype.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfactoryinterface.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlibrary.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qplugin.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpluginloader.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/quuid.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstractstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qabstracttransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeventtransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfinalstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qhistorystate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsignaltransition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstate.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstatemachine.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qatomic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qexception.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuture.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfutureinterface.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuturesynchronizer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qfuturewatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qgenericatomic.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmutex.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qreadwritelock.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qresultstore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrunnable.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsemaphore.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthread.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthreadpool.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qthreadstorage.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qwaitcondition.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qalgorithms.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydataops.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qarraydatapointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbitarray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraylist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qbytearraymatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcache.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qchar.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcollator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineoption.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcommandlineparser.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcontainerfwd.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcontiguouscache.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qcryptographichash.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qeasingcurve.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qelapsedtimer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qhash.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qiterator.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qline.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlinkedlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qlocale.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmap.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmargins.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qmessageauthenticationcode.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpair.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qpoint.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qqueue.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrect.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qrefcount.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qregexp.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qregularexpression.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qscopedpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qscopedvaluerollback.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qset.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qshareddata.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsharedpointer.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qsize.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstack.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstring.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringbuilder.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringlist.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qstringmatcher.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtextboundaryfinder.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtimezone.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvarlengtharray.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qvector.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qxmlstream.h \
		../../../Qt5.5.0/5.5/clang_64/lib/QtCore.framework/Headers/qtcoreversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sha1.o sha1.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_appmodel.o: moc_appmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_appmodel.o moc_appmodel.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/OpenVaccine/bin || mkdir -p $(INSTALL_ROOT)/opt/OpenVaccine/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/OpenVaccine/bin/OpenVaccine.app
	
	-$(INSTALL_DIR) OpenVaccine.app $(INSTALL_ROOT)/opt/OpenVaccine/bin/OpenVaccine.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/OpenVaccine/bin/OpenVaccine.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/OpenVaccine/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

